// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PulseSubscriptions.Data.PostgreSql;

#nullable disable

namespace PulseSubscriptions.Data.PostgreSql.Migrations
{
    [DbContext(typeof(PulseSubscriptionsDbContext))]
    [Migration("20260402203138_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PulseSubscriptions.Data.PostgreSql.Models.PulseSubscriptionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("DeclineRate")
                        .HasColumnType("boolean")
                        .HasColumnName("decline_rate");

                    b.Property<bool>("ExpiredApi")
                        .HasColumnType("boolean")
                        .HasColumnName("expired_api");

                    b.Property<bool>("InactiveMerchant")
                        .HasColumnType("boolean")
                        .HasColumnName("inactive_merchant");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("WebhookFailures")
                        .HasColumnType("boolean")
                        .HasColumnName("webhook_failures");

                    b.HasKey("Id");

                    b.ToTable("pulse_subscriptions", "pulse");
                });
#pragma warning restore 612, 618
        }
    }
}
